#!/usr/bin/env bash
set -eu -o pipefail

. ~/Scripts/development/woocommerce wc1c

[[ -d ~/Projects/wc1c ]] || svn co http://plugins.svn.wordpress.org/woocommerce-and-1centerprise-data-exchange/trunk/ ~/Projects/wc1c

if [[ ! -L ./wp-content/plugins/woocommerce-and-1centerprise-data-exchange ]]; then
  ln -fsT ~/Projects/wc1c ./wp-content/plugins/woocommerce-and-1centerprise-data-exchange
  wp plugin activate woocommerce-and-1centerprise-data-exchange
fi

mkdir -p ~/Projects/wc1c/uploads/catalog
ln -fsT ~/Projects/wc1c/uploads ./wp-content/uploads/woocommerce-1c
