#!/usr/bin/env bash
set -eu -o pipefail

project_dir=`readlink -f .`
. ~/Scripts/development/woocommerce ${project_dir##*/}

if [[ ! -L ./wp-content/plugins/woocommerce-and-1centerprise-data-exchange ]]; then
  ln -s ~/Projects/wc1c ./wp-content/plugins/woocommerce-and-1centerprise-data-exchange
  wp plugin activate woocommerce-and-1centerprise-data-exchange
fi

mkdir -p ~/Projects/wc1c/uploads/catalog
ln -fsT ~/Projects/wc1c/uploads ./wp-content/uploads/woocommerce-1c
